# Stage 1: Cache Gradle dependencies
FROM gradle:latest AS cache
RUN mkdir -p /home/gradle/cache_home
ENV GRADLE_USER_HOME=/home/gradle/cache_home

WORKDIR /home/gradle/app

# Copy necessary files to cache dependencies
COPY gradle/ /home/gradle/app/gradle/
COPY gradle.properties settings.gradle.kts /home/gradle/app/
COPY build.gradle.kts /home/gradle/app/

RUN gradle --project-dir . dependencies --no-daemon --refresh-dependencies --stacktrace

# Stage 2: Build Application
FROM gradle:latest AS build
COPY --from=cache /home/gradle/cache_home /home/gradle/.gradle
WORKDIR /home/gradle/app
COPY . /home/gradle/app/

RUN gradle --project-dir . buildFatJar --no-daemon --stacktrace

# Stage 3: Run the Application
FROM amazoncorretto:22 AS runtime
EXPOSE 8080
WORKDIR /app
COPY --from=build /home/gradle/app/build/libs/*.jar /app/ktor-app.jar

ENTRYPOINT ["java", "-jar", "/app/ktor-app.jar"]
