ktor:
  deployment:
    port: 8080

  application:
    modules:
      - onlytrade.app.ApplicationKt.module

  storage:
    jdbcURL: "jdbc:postgresql://localhost:5432/ot_dev"
    driverClassName: "org.postgresql.Driver"
    user: "postgres"
    password: "1994"